- .github/workflows/ci.yml
This pull request includes changes to the Continuous Integration (CI) workflow configuration in `.github/workflows/ci.yml`. The changes involve switching from using Perl to Purl for modifying the `compose.yml` file, and adding steps to download and install Purl. 
Here are the key changes:
* In `.github/workflows/ci.yml`, added a new step to download Purl, a command-line tool used for string manipulation. This step downloads the latest Purl release from GitHub and extracts the downloaded tarball to the `/tmp` directory.
* Added another step to move the Purl binary from `/tmp` to `/usr/local/bin/`, making it available for use in the workflow.
* Modified the step that updates the `compose.yml` file. Previously, this step used Perl for string replacement in the file. Now, it uses Purl with …
> Add purl download and move files for purl installation

- renovate.json
This pull request includes a change to the `renovate.json` file. The change introduces a new package rule for Docker data sources, specifically for the `nginx` package. This rule uses a regular expression for versioning, which appears to enforce a certain pattern for major, minor, and patch versions.
> Add packageRules for docker nginx versioning in renovate.json

- .github/workflows/ci.yml
This pull request includes a change to the `.github/workflows/ci.yml` file. The change expands the list of files that trigger the CI workflow, ensuring that any changes to `compose.yml` and `webapp/compose.yml` will also cause the workflow to run.
> Add compose.yml files to CI workflow paths

- webapp/compose.yml
- webapp/go/Dockerfile
This pull request includes several changes to the `webapp` service configuration and Docker setup. The most important changes involve updating the Dockerfile for the Go application and modifying the `compose.yml` file to ensure proper service dependencies.
* Added Dockerfile syntax directive at the top. (`webapp/go/Dockerfile`)
* Changed `RUN go mod download` to include the `-x` flag for more detailed output. (`webapp/go/Dockerfile`)
* Replaced `CMD ./app` with `ENTRYPOINT [ "./app" ]` to set the entry point for the container. (`webapp/go/Dockerfile`)
* Added `depends_on` section to ensure the MySQL service starts before the main service. (`webapp/compose.yml`)
> Add mysql service dependency in compose.yml and update go Dockerfile

- .github/workflows/ci.yml
- README.md
- bench/Dockerfile
- bench/Dockerfile-payment
- bench/Dockerfile-shipment
- bench/run.sh
- compose.yml
This pull request includes significant updates to the Dockerfiles for the benchmark services and minor changes to the `compose.yml` and `run.sh` files. The most important changes include restructuring the Dockerfiles to use multi-stage builds, adding non-privileged users, and updating the `compose.yml` to specify build targets.
* [`bench/Dockerfile`](diffhunk://#diff-93465fc7273c359e8aee7c9a379b6d47fde6ba561161dd45b7cc2a6594ee1304L1-R49): Restructured to use multi-stage builds, added non-privileged user, and updated the `ENTRYPOINT` to use `/run.sh`.
* [`bench/Dockerfile-payment`](diffhunk://#diff-9fdead0afe11f5b902967da49b0f3f1bcdc149b1e3b113d728264eac522bce39L1-R46): Restructured to use multi-stage builds, added non-privileged user, and updated the `ENTRYPOINT` to use `/bin/server`.
* …
> Refactor Dockerfile to use multi-stage builds and add non-privileged user

- webapp/ruby/Dockerfile
This pull request includes several updates to the `webapp/ruby/Dockerfile` to improve Docker image build efficiency and ensure consistency in the application startup process.
* Added Dockerfile syntax version declaration at the top of the file (`#syntax=docker/dockerfile:1`).
* Implemented build cache mounts to speed up `apt-get update` and package installation (`--mount=type=cache,target=/var/lib/apt,sharing=locked` and `--mount=type=cache,target=/var/cache/apt,sharing=locked`).
* Changed the way `Gemfile` and `Gemfile.lock` are copied to the Docker image to ensure they are in the correct directory before running `bundle install`.
* Replaced `CMD` with `ENTRYPOINT` to ensure the application always starts with the specified command (`bundle exec rackup -p 8000 -o 0.0.0.0`).
> Update Dockerfile for caching layers and change CMD to ENTRYPOINT

- bench/Dockerfile
- bench/Dockerfile-payment
- bench/Dockerfile-shipment
This pull request includes updates to the `bench` Dockerfiles to ensure compatibility with a specific version of the Alpine Linux base image. The most important changes are as follows:
Updates to Alpine Linux version:
* [`bench/Dockerfile`](diffhunk://#diff-93465fc7273c359e8aee7c9a379b6d47fde6ba561161dd45b7cc2a6594ee1304L16-R16): Changed the base image from `alpine:latest` to `alpine:3.20` to ensure consistent build environments.
* [`bench/Dockerfile-payment`](diffhunk://#diff-9fdead0afe11f5b902967da49b0f3f1bcdc149b1e3b113d728264eac522bce39L15-R15): Updated the base image from `alpine:latest` to `alpine:3.20` to align with the main Dockerfile and maintain consistency.
* [`bench/Dockerfile-shipment`](diffhunk://#diff-e667da3a2697f79610484a124c51b511d213dd235ef3fbff83e749468b94cf60L15-R15): …
> Update base image in Dockerfiles from alpine:latest to alpine:3.20

- webapp/go/main.go
This pull request includes a small change to the `postLogin` function in the `webapp/go/main.go` file. The change sets the `Secure` option of the session to `false`.
* [`webapp/go/main.go`](diffhunk://#diff-871eb89e86e63e7eca84f0075cba1a75574a11341cd89d39c7891864d2b085b9R2214): Modified the `postLogin` function to set `session.Options.Secure` to `false`.
> set session.Options.Secure to false for docker

- Makefile
- initial-data/.gitignore
This pull request includes changes to the `Makefile` and `.gitignore` to streamline the setup process and manage initial data more efficiently. The most important changes include updating the initialization process, adding new tasks for handling initial data, and updating the `.gitignore` file.
Improvements to initialization and setup:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L29-R33): Removed the dependency on `webapp/sql/90_initial.sql` and added `setup-initial-data` and `clean-zip` tasks to handle initial data setup and cleanup. [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L29-R33) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R56-R68)
Updates to …
> Refactor Makefile for improved initial data setup and cleanup commands

- .github/workflows/ci.yml
This pull request includes changes to the CI workflow to enhance the handling and checking of benchmark results.
Enhancements to CI workflow:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL94-R98): Modified the benchmark command to output results to `benchmark_output.json` and added a step to check the benchmark result using `jq` to determine if the benchmark passed or failed.
> Add benchmark output logging and result checking in CI workflow

- .github/workflows/ci.yml
This pull request includes an important change to the CI workflow configuration to improve the handling of benchmark results. The update ensures that the benchmark output file exists before checking its contents and properly exits if the benchmark fails.
Changes to CI workflow:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL98-R105): Added a check to ensure `benchmark_output.json` exists and modified the benchmark result check to properly exit if the benchmark fails.
> Add checks for benchmark_output.json existence and validation in CI

- bench/asset/asset.go
- bench/scenario/campaign.go
- bench/scenario/normal.go
- bench/server/shipment.go
This pull request includes several changes to update the `math/rand` package to `math/rand/v2` and to replace the deprecated `rand.Intn` function with the new `rand.IntN` function across multiple files.
* [`bench/asset/asset.go`](diffhunk://#diff-06d0c7f4a583b248109ed275ab18354451517c4c0df33b9aa8f16bf95f68fd28L10-R10): Updated import from `math/rand` to `math/rand/v2` and replaced `rand.Intn` with `rand.IntN` in multiple functions, including `GetRandomActiveSellerIDs`, `GetRandomBuyerIDs`, `GetRandomImageFileName`, `GetRandomRootCategory`, `GetRandomChildCategory`, `GetRandomChildCategoryByParentID`, and `GenText`. [[1]](diffhunk://#diff-06d0c7f4a583b248109ed275ab18354451517c4c0df33b9aa8f16bf95f68fd28L10-R10) [[2]](diffhunk://#diff-06d0c7f4a583b248109ed275ab18354451517c4c0df33b9aa8f16bf95f …
> replace math/rand with math/rand/v2

- webapp/go/go.mod
- webapp/go/main.go
This pull request includes several changes to the `webapp/go` module to enhance session management and update dependencies. The most important changes involve adding a new dependency, modifying the session store initialization, and updating the import statements.
* Added `github.com/gorilla/securecookie v1.1.2` to the `go.mod` file and removed the redundant indirect requirement. (`webapp/go/go.mod`)
* Updated the import statements in `main.go` to include `github.com/gorilla/securecookie`. (`webapp/go/main.go`)
* Modified the session store initialization to use `securecookie.CodecsFromPairs` for enhanced security and set additional session options. (`webapp/go/main.go`)
* Removed the line setting `session.Options.Secure` to `false` in the `getSession` function, as this is now managed by …
> update session managemnent for unsecure cookie

- webapp/go/go.mod
This pull request includes a small change to the `webapp/go/go.mod` file. The change removes the `toolchain go1.23.0` line to simplify the module configuration.
* [`webapp/go/go.mod`](diffhunk://#diff-318aa8c326576614a6f71c64bcfcb0995df9f21d379aaddcc68cd019d275eadbL5-L6): Removed the `toolchain go1.23.0` line.
> Remove toolchain specification from go.mod file

- provisioning/roles/bootstrap/files/home/isucon/add_hosts.sh
- provisioning/roles/bootstrap/tasks/main.yml
- provisioning/roles/webapp.ruby/tasks/main.yml
This pull request includes several changes to the provisioning scripts and tasks to enhance automation and environment setup. The most important changes involve adding a script to automatically update the `/etc/hosts` file and modifying the Ruby web application setup.
Automation enhancements:
* [`provisioning/roles/bootstrap/files/home/isucon/add_hosts.sh`](diffhunk://#diff-32211863f116bbbc31cf4e0e163856389471bd0735d4a884f4bdf61013dfdfd9R1-R24): Added a new script to automatically append IP addresses and domains to the `/etc/hosts` file.
* [`provisioning/roles/bootstrap/tasks/main.yml`](diffhunk://#diff-1b404a10aacc5570779bcd56a2b74a61215a20110e68f67288471129d423df91R51-R58): Added a task to copy the new `add_hosts.sh` script to the target machine.
Environment setup improvements:
* …
> Add script to update /etc/hosts and modify bundle install command

- README.md
This pull request includes a small change to the `README.md` file. The change adds instructions for using a shell script to update hosts.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R332-R337): Added instructions for using the `/home/isucon/add_hosts.sh` shell script to update hosts.
> Add note about using add_hosts.sh script for host management

- README.md
This pull request adds new documentation to the `README.md` file, providing detailed instructions for setting up and using AMI instances for both competitors and benchmarkers.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R14-R46): Added a new section titled "AMI" that includes AMI IDs, recommended instance types, and commands for modifying `/etc/hosts`, updating TLS certificates, and running the benchmarker for the isucari application.
> Add AMI information and setup instructions to README.md

- webapp/go/main.go
This pull request includes a small but significant change to the `webapp/go/main.go` file. The change enhances the security of session cookies by making them HttpOnly.
* [`webapp/go/main.go`](diffhunk://#diff-871eb89e86e63e7eca84f0075cba1a75574a11341cd89d39c7891864d2b085b9L279-R279): Changed the `SameSite` attribute to `HttpOnly` in the session options to improve security.
> fix session options

- README.md
This pull request includes a small change to the `README.md` file. The change updates the AMI ID and name for the `isucon9-qualify-app` instance.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L19-R20): Updated the AMI ID and name for the `isucon9-qualify-app` instance to `ami-01e5d6ed3030d5df4` and `isucon9-qualify-app-20241013`, respectively.
> Update AMI ID and name for isucon9-qualify-app in README.md

- .github/workflows/ci.yml
This pull request includes changes to the CI workflow configuration to ensure that logs are shown after the benchmark is run. The most important changes are:
CI Workflow Enhancements:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR96-R100): Added a step to show logs after running the benchmark, ensuring that the logs are available for debugging purposes.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL107-L111): Removed the redundant step to show logs that was previously placed before checking the benchmark result.
> Add log display step to CI workflow after benchmarks execution

- webapp/ruby/Dockerfile
- webapp/ruby/Gemfile
- webapp/ruby/Gemfile.lock
This pull request includes updates to the `Dockerfile` and `Gemfile` for the Ruby web application. The most important changes are:
* Updated the Ruby version in the `Dockerfile` from `3.3-slim` to `3.4-slim` to use the latest version.
* Added the `bigdecimal` gem to the `Gemfile` to support high-precision floating-point decimal arithmetic.
> Update Ruby version to 3.4, add bigdecimal gem in Gemfile and lockfile.

- .github/workflows/ci.yml
This pull request includes a small change to the `.github/workflows/ci.yml` file. The change improves the readability of the `Run the benchmark` step by breaking down the command into multiple lines.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL94-R107): Reformatted the `docker container run` command to span multiple lines for better readability.
> efactor benchmark run command for better readability in CI workflow

- .github/workflows/ci.yml
This pull request includes updates to the `.github/workflows/ci.yml` file to improve the detection of changes in the `ruby/` directory and handle updates to the `compose.yml` file more robustly.
Workflow improvements:
* Modified the `check-changes` step to use the base reference of the pull request for detecting changes, ensuring more accurate detection of changes in the `ruby/` directory.
* Updated the `Update compose.yml if changes are detected` step to use the `-fail` flag with the `purl` command, making the process more robust by failing on errors.
> Update CI workflow to check for changes in 'ruby/' directory

- .github/workflows/ci.yml
This pull request includes a small change to the `.github/workflows/ci.yml` file. The change modifies the output message when a benchmark fails to provide more specific information.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL123-R123): Changed the benchmark failure message to "Benchmark failed: pass is not true" for better clarity.
> Update CI workflow to log benchmark failure message

- .github/workflows/codeql.yml
This pull request includes an update to the `.github/workflows/codeql.yml` file to ensure the use of the latest Go version.
* Updated Go version from `1.22.x` to `1.24.1` in the `jobs:` section of the `.github/workflows/codeql.yml` file.
> Update Go version to 1.24.1 in CodeQL workflow configuration.

- webapp/go/main.go
This pull request includes a small change to the `webapp/go/main.go` file. The change updates the type of the `inArgs` variable from `[]interface{}` to `[]any`.
> webapp: Use "any" instead of "interface{}" for sqlx.In args

- webapp/go/Makefile
- webapp/go/go.mod
This pull request includes updates to the Go build process and dependencies for the `webapp/go` project. The most important changes ensure the build process is more robust and dependencies are updated to use the latest Go version.
* Updated the `Makefile` to include `go.mod` and `go.sum` as dependencies for the `isucari` target, ensuring the build process accounts for changes in module files. (`webapp/go/Makefile`, [webapp/go/MakefileL3-R3](diffhunk://#diff-78fd90c5e708a99f889e37f5576b333b067dbe215df2b36288f348a4bd46ed21L3-R3))
* Upgraded the Go version in `go.mod` from `1.23.0` to `1.24.0`, aligning the project with the latest features and improvements in the Go language. (`webapp/go/go.mod`, [webapp/go/go.modL3-R3](diffhunk://#diff-318aa8c326576614a6f71c64bcfcb0995df9f21d379aaddcc68cd019 …
> Update Makefile dependencies and bump Go version to 1.24.0

- webapp/go/main.go
This pull request updates the `webapp/go/main.go` file to improve the handling of static assets by introducing the use of a root directory object. The changes enhance error handling and simplify the file server setup.
* Introduced a `root` object using `os.OpenRoot("../public")` to manage the root directory for static assets, with proper error handling and cleanup using `defer`.
* Updated the file server setup to use `http.FileServerFS(root.FS())` instead of directly serving the directory with `http.FileServer(http.Dir("../public"))`, leveraging the new `root` object.
> use os.OpenRoot to serve static files

- .github/workflows/renovate-config-validator-ci.yml
This pull request updates the Renovate configuration validation workflow to ensure the latest version of the Renovate package is used.
* [`.github/workflows/renovate-config-validator-ci.yml`](diffhunk://#diff-e519a4bcca8b109726730f425f70681c1ebc03420db40b019c222ff042b1fd76L20-R20): Updated the `run` command to use `renovate@latest` instead of the default package version for validating `renovate.json`.
> update renovate-config-validator step to use renovate@latest

- renovate.json
This pull request updates the `renovate.json` configuration file to add new custom rules for managing PHP dependencies. The changes introduce additional regex-based configurations to handle version extraction and dependency management for PHP-related files.
* Added a new `customType: regex` configuration for files matching the pattern `/provisioning/roles/php/tasks/main.yml/`. This configuration uses `github-tags` as the datasource, targets the `php/php-src` dependency, and extracts versions using the regex pattern `^php-(?<version>.*). It matches strings in the format `php-install (?<currentValue>[0-9]+\.[0-9]+\.[0-9]+)`.
* Added another `customType: regex` configuration for the same file pattern (`/provisioning/roles/php/tasks/main.yml/`). This configuration also uses `github-tags` as …
> Add PHP version regex rules for renovate updates in provisioning role

- renovate.json
This pull request updates the Renovate configuration to improve the accuracy of version extraction for PHP dependencies. The changes involve switching the data source and updating the dependency name and version extraction template.
* Updated the `datasourceTemplate` from `php-version` to `github-tags` to use a more reliable data source for PHP versions. [[1]](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L67-R69) [[2]](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L79-R81)
* Changed the `depNameTemplate` from `php` to `php/php-src` to align with the new data source structure. [[1]](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L67-R69) …
> fix renovate php datasource

- provisioning/webapp.yml
This pull request updates the `provisioning/webapp.yml` file to enable support for Python and WebApp Python by uncommenting their respective entries.
Key change:
* [`provisioning/webapp.yml`](diffhunk://#diff-f85b7e9b54fa49cf44440d2b8a2de4acb9af7544b2807a38b520d6b816d90c63L15-R22): Uncommented the `python` and `webapp.python` entries to include them in the provisioning configuration.
> Uncomment python and webapp.python in provisioning/webapp.yml

- provisioning/webapp.yml
This pull request removes the `isucari.php.service` entry from the `provisioning/webapp.yml` file. This change likely reflects a deprecation or removal of the PHP-based service from the provisioning configuration.
> Remove isucari.php.service from webapp provisioning configuration

- webapp/python/app.py
`http_json_error` takes two parameters (error code and message), but only the error code was passed in specific call sites.
> Fix Python WebAPP Missing Parameter

- webapp/nodejs/src/utils.ts
This pull request updates the random string generation logic in the `secureRandomStr` function to use `randomInt` from the `crypto` module instead of `randomBytes`. This change simplifies the code and ensures each character is chosen independently and securely.
Random string generation update:
* [`webapp/nodejs/src/utils.ts`](diffhunk://#diff-c89483bd51bd4c314775d02515f51578915de4d47dd290fd163c3b8d9cda8bb3L1-R10): Replaced the use of `randomBytes` with `randomInt` for generating random characters in the `secureRandomStr` function, simplifying the implementation and maintaining cryptographic security.
> Use crypto.randomInt instead of randomBytes for secureRandomStr
